---
- name: Add yunion rpm repository
  get_url:
    url: https://iso.yunion.cn/yumrepo-3.6/yunion.repo
    dest: /etc/yum.repos.d/yunion.repo
  become: yes
  when:
  - is_centos_x86 is defined

- name: Install yunion common packages
  yum:
    state: latest
    name:
      - kernel-3.10.0-1062.4.3.el7.yn20191203
      - kernel-devel-3.10.0-1062.4.3.el7.yn20191203
      - kernel-headers-3.10.0-1062.4.3.el7.yn20191203
      - yunion-executor
  when:
  - is_centos_x86 is defined