---
- name: Setup repo mirrors
  include_role:
    name: utils/mirror

- name: Add yunion rpm repository
  get_url:
    url: "{{ yunion_yum_repo }}"
    dest: /etc/yum.repos.d/yunion.repo
  become: yes

- name: Remove the old yunion-executor-server package
  yum:
    name: yunion-executor-server
    state: absent
  when:
  - is_centos_x86 is defined

- name: Upgrade yunion common packages
  yum:
    name:
      - yunion-ocadm
      - yunion-climc
      - yunion-executor
    state: latest
  when:
  - is_centos_x86 is defined

- name: Restart yunion executor service
  service:
    name: "{{ item }}"
    enabled: yes
    state: restarted
  loop:
    - yunion-executor
